# Generated by Django 3.2.15 on 2022-10-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='applyTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegistrationNumber', models.CharField(max_length=32)),
                ('SerialNumber', models.CharField(max_length=32)),
                ('Organization', models.CharField(max_length=32)),
                ('StartTime', models.DateField()),
                ('EndTime', models.DateField()),
                ('JuridicalPerson', models.CharField(max_length=32)),
                ('ChargePerson', models.CharField(max_length=32)),
                ('ChargePhone', models.CharField(max_length=32)),
                ('UserName', models.CharField(max_length=32)),
                ('PublicKey', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='certTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegistrationNumber', models.CharField(max_length=32)),
                ('SerialNumber', models.CharField(max_length=32)),
                ('Organization', models.CharField(max_length=32)),
                ('StartTime', models.DateField()),
                ('EndTime', models.DateField()),
                ('JuridicalPerson', models.CharField(max_length=32)),
                ('ChargePerson', models.CharField(max_length=32)),
                ('ChargePhone', models.CharField(max_length=32)),
                ('UserName', models.CharField(max_length=32)),
                ('PublicKey', models.CharField(max_length=32)),
                ('CertPathName', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='crlTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SerialNumber', models.CharField(max_length=32)),
                ('Organization', models.CharField(max_length=32)),
                ('RevokeTime', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='userTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=32)),
                ('Password', models.CharField(max_length=32)),
                ('Email', models.CharField(max_length=32)),
                ('Sex', models.CharField(max_length=1)),
                ('Birthday', models.DateField()),
                ('Phone', models.CharField(max_length=32)),
                ('Salt', models.CharField(max_length=32)),
            ],
        ),
    ]
