# Generated by Django 3.2.15 on 2022-10-20 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuedata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='Password',
            field=models.CharField(max_length=64),
        ),
    ]
