# Generated by Django 3.2.15 on 2022-10-20 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuedata', '0002_alter_usertable_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='Password',
            field=models.BinaryField(max_length=64),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='Salt',
            field=models.BinaryField(max_length=32),
        ),
    ]
