# Generated by Django 3.2.15 on 2022-10-22 08:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vuedata', '0003_auto_20221020_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='regDay',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applytable',
            name='SerialNumber',
            field=models.CharField(max_length=64),
        ),
    ]
