# Generated by Django 3.2.15 on 2022-10-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuedata', '0004_auto_20221022_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applytable',
            name='PublicKey',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='certtable',
            name='PublicKey',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='certtable',
            name='SerialNumber',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='crltable',
            name='SerialNumber',
            field=models.CharField(max_length=64),
        ),
    ]
