# Generated by Django 3.2.15 on 2022-10-22 14:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vuedata', '0005_auto_20221022_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='regDay',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
