# Generated by Django 3.2.15 on 2022-11-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuedata', '0006_alter_usertable_regday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applytable',
            name='PublicKey',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='certtable',
            name='PublicKey',
            field=models.CharField(max_length=600),
        ),
    ]
